### ISSUE TITLE
psycopg 2.8.3

### ISSUE THREAD

**Issue by ale-rt** [euphorie/Euphorie#201]
Upgrade psycopg2 to avoid this warning:
```
The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary"
```

**Comment by ale-rt** [comment]
I am testing this locally, I will make a PR when I am happy with it

**Comment by pysailor** [comment]
@ale-rt Is this still a thing? Or can we close this?

**Comment by ale-rt** [comment]
In this commit https://github.com/euphorie/Euphorie/commit/a529fceccc15a699baeec0b0e61fe08b0a1ef873 a pin for psycopg2-binary 2.8.6 was added:
- https://github.com/euphorie/Euphorie/blob/e6ff4d283346b96a72c5e424ad5a343be13520d3/versions.cfg#L25
So this can be closed
