### ISSUE TITLE
Couldn't find index page for 'pyrtf-ng' (maybe misspelled?)

### ISSUE THREAD

**Issue by rebelx** [euphorie/Euphorie#254]
When trying to install Euphorie as part of a Plone 5.2 site, I get the following error message and the install aborts:

` Couldn't find index page for 'pyrtf-ng' (maybe misspelled?)`

Alternatively I tried to install pyrtf-ng via pip, which was succesfull, but the buildout still fails with the same error. Any clues on how to fix this?

**Comment by pysailor** [comment]
pyrtf-ng is no no longer used, and no longer required via `setup.py`.
