### ISSUE TITLE
TinyMCE Image dialog for introduction of Survey versions

### ISSUE THREAD

**Issue by jcbrand** [euphorie/Euphorie#58]
Apparently the French would like to have a logo/image for the rich text introduction of a survey.

Would it be possible to enable an image widget for TinyMCE for that field? 

Alex would like it to be restricted to only externally hosted images. Doable?

Ref: 5880

**Comment by wichert** [comment]
Is this still relevant?

**Comment by cornae** [comment]
I have no idea actually.
