### ISSUE TITLE
Navigation inconsistency

### ISSUE THREAD

**Issue by wichert** [euphorie/Euphorie#8]
When editing a new version of a survey, the root of the left hand navigation points to the sector, not the survey version. As a result, when editing and clicking on the root to get back, I land on the main currently published version and if I continue to edit, I am editing this version instead of the new one.

Later comment:

> There is actually no single root of the navtree - as you say. The main level of the navigation lists all surveys. The problem is a redirect that happens when I click one of these surveys. The survey contains versions and it appears to me that if I click the survey, I am always redirected to the "standard" version, even if I was currently working on my "second version". This leads to a problem, because it is not obvious to me that while I was just editing risks/modules on my "second version", I click the survey, am redirected to the "standard version" and continue editing there.

**Comment by pysailor** [comment]
Closing as wontfix / obsolete
